<?php
declare(strict_types=1);

// --- BUSINESS LOGIC ---
$pageTitle = "Week 3: The Match Expression & Strictness";

$httpCode = 404;

// PHP 8 'match' expression is cleaner than switch, returns a value, and uses strict === comparison!
$responseMeaning = match($httpCode) {
    200, 201 => "Success: Application processing finished gracefully.",
    400 => "Client Error: Bad Request generated by invalid input.",
    403 => "Security Lockout: Access is strictly forbidden.",
    404 => "Routing Error: Missing resource.",
    500 => "Critical Infrastructure Failure.",
    default => "Unknown HTTP status."
};
// --- END LOGIC ---

require_once __DIR__ . '/../includes/header.php';
?>
<div class="content-box">
    <h2>Server Response Handler</h2>
    <p>Evaluating standard server codes using the PHP 8+ strict <code>match()</code> structure.</p>
</div>

<div class="info-box">
    <strong>Simulated Traffic:</strong> Returning HTTP <code><?= htmlspecialchars((string)$httpCode) ?></code><br>
    <strong>System Diagnosis:</strong> <?= htmlspecialchars($responseMeaning) ?>
</div>

<h3>Strict vs Loose Comparison Hazards</h3>
<table>
    <tr><th>Condition</th><th>Loose (==)</th><th>Strict (===)</th></tr>
    <tr><td><code>"" == 0</code></td><td><span style="color:red">TRUE (Bad)</span></td><td><span style="color:green">FALSE (Safe)</span></td></tr>
    <tr><td><code>"123" == 123</code></td><td><span style="color:red">TRUE</span></td><td><span style="color:green">FALSE</span></td></tr>
</table>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>