<?php
// references_data.php
// PHP Map containing official docs and snippets for each week

return [
    1 => ['url' => 'https://www.php.net/manual/pt_BR/install.php', 'title' => 'Instalação e Ambiente', 'snippet' => "<?php\nphpinfo();\n?>"],
    2 => ['url' => 'https://www.php.net/manual/pt_BR/language.types.php', 'title' => 'Variáveis e Tipos', 'snippet' => "<?php\n\$name = \"PHP 8\";\nvar_dump(is_string(\$name)); // bool(true)\n?>"],
    3 => ['url' => 'https://www.php.net/manual/pt_BR/language.operators.php', 'title' => 'Operadores', 'snippet' => "<?php\n\$result = match(true) {\n    \$a === \$b => 'Estritamente Igual',\n    default => 'Diferente'\n};\n?>"],
    4 => ['url' => 'https://www.php.net/manual/pt_BR/language.types.string.php', 'title' => 'Strings', 'snippet' => "<?php\n\$greeting = sprintf(\"Olá, %s!\", \$user);\n?>"],
    5 => ['url' => 'https://www.php.net/manual/pt_BR/language.control-structures.php', 'title' => 'Estruturas de Controle', 'snippet' => "<?php\nif (\$age >= 18) {\n    echo 'Acesso Permitido';\n}\n?>"],
    6 => ['url' => 'https://www.php.net/manual/pt_BR/language.types.array.php', 'title' => 'Arrays (Vetores)', 'snippet' => "<?php\n// Desestruturação\n[\$driver, \$port] = ['mysql', 3306];\n?>"],
    7 => ['url' => 'https://www.php.net/manual/pt_BR/control-structures.foreach.php', 'title' => 'Laços de Repetição', 'snippet' => "<?php\nforeach(\$users as \$id => \$name) {\n    echo \"Usuário \$id: \$name\";\n}\n?>"],
    8 => ['url' => 'https://www.php.net/manual/pt_BR/ref.array.php', 'title' => 'Funções de Array', 'snippet' => "<?php\n\$mapped = array_map(fn(\$x) => \$x * 2, [1, 2, 3]);\n?>"],
    9 => ['url' => 'https://www.php.net/manual/pt_BR/language.functions.php', 'title' => 'Funções', 'snippet' => "<?php\nfunction soma(int \$a, int \$b): int {\n    return \$a + \$b;\n}\n?>"],
    10=> ['url' => 'https://www.php.net/manual/pt_BR/functions.anonymous.php', 'title' => 'Escopo e Funções Anônimas', 'snippet' => "<?php\n\$tax = 0.5;\n\$calc = function(\$price) use (\$tax) {\n    return \$price + (\$price * \$tax);\n};\n?>"],
    11=> ['url' => 'https://www.php.net/manual/pt_BR/language.variables.superglobals.php', 'title' => 'Superglobais', 'snippet' => "<?php\nvar_dump(\$_SERVER['HTTP_HOST']);\nvar_dump(\$_GET['id'] ?? 1);\n?>"],
    12=> ['url' => 'https://www.php.net/manual/pt_BR/tutorial.forms.php', 'title' => 'Manipulação de Formulários', 'snippet' => "<?php\n\$name = filter_input(INPUT_POST, 'name', FILTER_SANITIZE_STRING);\n?>"],
    13=> ['url' => 'https://www.php.net/manual/pt_BR/features.sessions.php', 'title' => 'Sessões', 'snippet' => "<?php\nsession_start();\n\$_SESSION['user_id'] = 404;\n?>"],
    14=> ['url' => 'https://www.php.net/manual/pt_BR/features.cookies.php', 'title' => 'Cookies', 'snippet' => "<?php\nsetcookie('theme', 'dark', time() + 3600, '/', '', true, true);\n?>"],
    15=> ['url' => 'https://www.php.net/manual/pt_BR/ref.filesystem.php', 'title' => 'Sistema de Arquivos', 'snippet' => "<?php\nfile_put_contents('log.txt', \"Erro registrado!\\n\", FILE_APPEND);\n?>"],
    16=> ['url' => 'https://www.php.net/manual/pt_BR/features.file-upload.php', 'title' => 'Upload de Arquivos', 'snippet' => "<?php\nmove_uploaded_file(\$_FILES['img']['tmp_name'], './upload/' . \$fileName);\n?>"],
    17=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.php', 'title' => 'Introdução a POO', 'snippet' => "<?php\nclass Usuario {\n    public string \$nome;\n}\n?>"],
    18=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.visibility.php', 'title' => 'Visibilidade e Construtores', 'snippet' => "<?php\nclass Servico {\n    public function __construct(private string \$apiKey) {}\n}\n?>"],
    19=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.inheritance.php', 'title' => 'Herança', 'snippet' => "<?php\nclass Admin extends Usuario {\n    public function getRole() { return 'Admin'; }\n}\n?>"],
    20=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.interfaces.php', 'title' => 'Interfaces', 'snippet' => "<?php\ninterface Logger {\n    public function log(string \$msg);\n}\n?>"],
    21=> ['url' => 'https://www.php.net/manual/pt_BR/book.pdo.php', 'title' => 'Básico de SQL', 'snippet' => "CREATE TABLE users (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    email VARCHAR(255) UNIQUE NOT NULL\n);"],
    22=> ['url' => 'https://www.php.net/manual/pt_BR/pdo.connections.php', 'title' => 'Conexão PDO', 'snippet' => "<?php\n\$pdo = new PDO('mysql:host=localhost;dbname=test', 'usuario', 'senha');\n?>"],
    23=> ['url' => 'https://www.php.net/manual/pt_BR/pdo.prepared-statements.php', 'title' => 'Instruções Preparadas', 'snippet' => "<?php\n\$stmt = \$pdo->prepare('SELECT * FROM users WHERE id = ?');\n\$stmt->execute([\$id]);\n?>"],
    24=> ['url' => 'https://www.php.net/manual/pt_BR/pdostatement.execute.php', 'title' => 'Operações CRUD', 'snippet' => "<?php\n\$stmt = \$pdo->prepare(\"INSERT INTO users (name) VALUES (:name)\");\n\$stmt->execute(['name' => \$data]);\n?>"],
    25=> ['url' => 'https://www.php.net/manual/pt_BR/book.pdo.php', 'title' => 'Consultas JOIN', 'snippet' => "SELECT u.name, p.title \nFROM users u \nJOIN posts p ON u.id = p.user_id;"],
    26=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.architecture.php', 'title' => 'Padrão MVC', 'snippet' => "<?php\n// Router invoca o Controller, passa dados do Model para a View\n\$controller = new UserController(new UserModel());\n?>"],
    27=> ['url' => 'https://www.php.net/manual/pt_BR/reserved.variables.server.php', 'title' => 'Roteamento', 'snippet' => "<?php\n\$uri = parse_url(\$_SERVER['REQUEST_URI'], PHP_URL_PATH);\nif (\$uri === '/sobre') { require 'sobre.php'; }\n?>"],
    28=> ['url' => 'https://www.php.net/manual/pt_BR/language.basic-syntax.phpmode.php', 'title' => 'Templates', 'snippet' => "<h1><?= htmlspecialchars(\$title) ?></h1>"],
    29=> ['url' => 'https://www.php.net/manual/pt_BR/function.password-hash.php', 'title' => 'Hashing de Senha', 'snippet' => "<?php\n\$hash = password_hash('senha_secreta_123', PASSWORD_ARGON2ID);\n?>"],
    30=> ['url' => 'https://www.php.net/manual/pt_BR/function.password-verify.php', 'title' => 'Autenticação', 'snippet' => "<?php\nif (password_verify(\$tentativaSenha, \$hashUsuario)) {\n    \$_SESSION['auth'] = true;\n}\n?>"],
    31=> ['url' => 'https://www.php.net/manual/pt_BR/features.sessions.php', 'title' => 'Autorização e Papéis', 'snippet' => "<?php\nif (!in_array('admin', \$_SESSION['roles'])) {\n    http_response_code(403);\n    die('Proibido');\n}\n?>"],
    32=> ['url' => 'https://www.php.net/manual/pt_BR/security.php', 'title' => 'Segurança Web', 'snippet' => "<?php\n// Prevenir XSS\n\$safe = htmlspecialchars(\$unsafeStr, ENT_QUOTES, 'UTF-8');\n?>"],
    33=> ['url' => 'https://www.php.net/manual/pt_BR/book.json.php', 'title' => 'JSON e REST', 'snippet' => "<?php\nheader('Content-Type: application/json');\necho json_encode(['status' => 'success', 'data' => []]);\n?>"],
    34=> ['url' => 'https://www.php.net/manual/pt_BR/book.curl.php', 'title' => 'APIs Externas (cURL)', 'snippet' => "<?php\n\$ch = curl_init('https://api.github.com/users/octocat');\ncurl_setopt(\$ch, CURLOPT_RETURNTRANSFER, true);\n\$response = curl_exec(\$ch);\n?>"],
    35=> ['url' => 'https://www.php.net/manual/pt_BR/reserved.variables.server.php', 'title' => 'Construindo APIs', 'snippet' => "<?php\nif (\$_SERVER['REQUEST_METHOD'] === 'POST') {\n    // Criar recurso\n}\n?>"],
    36=> ['url' => 'https://www.php.net/manual/pt_BR/language.namespaces.rationale.php', 'title' => 'Composer e PSR-4', 'snippet' => "<?php\nrequire 'vendor/autoload.php';\nuse App\\Models\\Usuario;\n?>"],
    37=> ['url' => 'https://www.php.net/manual/pt_BR/book.errorfunc.php', 'title' => 'Tratamento de Erros', 'snippet' => "<?php\ntry {\n    // lógica arriscada\n} catch (Exception \$e) {\n    error_log(\$e->getMessage());\n}\n?>"],
    38=> ['url' => 'https://www.php.net/manual/pt_BR/book.datetime.php', 'title' => 'Datas e Horários', 'snippet' => "<?php\n\$dt = new DateTime();\necho \$dt->format('Y-m-d H:i:s');\n?>"],
    39=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.php', 'title' => 'Arquitetura', 'snippet' => "<?php\n// Padrões de projeto, Injeção de Dependência\n\$app = new Application(new Database());\n?>"],
    40=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.php', 'title' => 'Implementação', 'snippet' => "<?php\n// Testes finais e verificações de implantação\n?>"]
];
