<?php
// references_data.php
// PHP Map containing official docs and snippets for each week

return [
    1 => ['url' => 'https://www.php.net/manual/pt_BR/install.php', 'title' => 'Installation & Environment', 'snippet' => "<?php\nphpinfo();\n?>"],
    2 => ['url' => 'https://www.php.net/manual/pt_BR/language.types.php', 'title' => 'Variables & Types', 'snippet' => "<?php\n\$name = \"PHP 8\";\nvar_dump(is_string(\$name)); // bool(true)\n?>"],
    3 => ['url' => 'https://www.php.net/manual/pt_BR/language.operators.php', 'title' => 'Operators', 'snippet' => "<?php\n\$result = match(true) {\n    \$a === \$b => 'Strictly Equal',\n    default => 'Different'\n};\n?>"],
    4 => ['url' => 'https://www.php.net/manual/pt_BR/language.types.string.php', 'title' => 'Strings', 'snippet' => "<?php\n\$greeting = sprintf(\"Hello, %s!\", \$user);\n?>"],
    5 => ['url' => 'https://www.php.net/manual/pt_BR/language.control-structures.php', 'title' => 'Control Structures', 'snippet' => "<?php\nif (\$age >= 18) {\n    echo 'Access Granted';\n}\n?>"],
    6 => ['url' => 'https://www.php.net/manual/pt_BR/language.types.array.php', 'title' => 'Arrays', 'snippet' => "<?php\n// Destructuring\n[\$driver, \$port] = ['mysql', 3306];\n?>"],
    7 => ['url' => 'https://www.php.net/manual/pt_BR/control-structures.foreach.php', 'title' => 'Loops', 'snippet' => "<?php\nforeach(\$users as \$id => \$name) {\n    echo \"User \$id: \$name\";\n}\n?>"],
    8 => ['url' => 'https://www.php.net/manual/pt_BR/ref.array.php', 'title' => 'Array Functions', 'snippet' => "<?php\n\$mapped = array_map(fn(\$x) => \$x * 2, [1, 2, 3]);\n?>"],
    9 => ['url' => 'https://www.php.net/manual/pt_BR/language.functions.php', 'title' => 'Functions', 'snippet' => "<?php\nfunction sum(int \$a, int \$b): int {\n    return \$a + \$b;\n}\n?>"],
    10=> ['url' => 'https://www.php.net/manual/pt_BR/functions.anonymous.php', 'title' => 'Scope & Anonymous', 'snippet' => "<?php\n\$tax = 0.5;\n\$calc = function(\$price) use (\$tax) {\n    return \$price + (\$price * \$tax);\n};\n?>"],
    11=> ['url' => 'https://www.php.net/manual/pt_BR/language.variables.superglobals.php', 'title' => 'Superglobals', 'snippet' => "<?php\nvar_dump(\$_SERVER['HTTP_HOST']);\nvar_dump(\$_GET['id'] ?? 1);\n?>"],
    12=> ['url' => 'https://www.php.net/manual/pt_BR/tutorial.forms.php', 'title' => 'Forms Handling', 'snippet' => "<?php\n\$name = filter_input(INPUT_POST, 'name', FILTER_SANITIZE_STRING);\n?>"],
    13=> ['url' => 'https://www.php.net/manual/pt_BR/features.sessions.php', 'title' => 'Sessions', 'snippet' => "<?php\nsession_start();\n\$_SESSION['user_id'] = 404;\n?>"],
    14=> ['url' => 'https://www.php.net/manual/pt_BR/features.cookies.php', 'title' => 'Cookies', 'snippet' => "<?php\nsetcookie('theme', 'dark', time() + 3600, '/', '', true, true);\n?>"],
    15=> ['url' => 'https://www.php.net/manual/pt_BR/ref.filesystem.php', 'title' => 'File System', 'snippet' => "<?php\nfile_put_contents('log.txt', \"Error logged!\\n\", FILE_APPEND);\n?>"],
    16=> ['url' => 'https://www.php.net/manual/pt_BR/features.file-upload.php', 'title' => 'File Uploads', 'snippet' => "<?php\nmove_uploaded_file(\$_FILES['img']['tmp_name'], './upload/' . \$fileName);\n?>"],
    17=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.php', 'title' => 'Intro to OOP', 'snippet' => "<?php\nclass User {\n    public string \$name;\n}\n?>"],
    18=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.visibility.php', 'title' => 'Visibility & Constructors', 'snippet' => "<?php\nclass Service {\n    public function __construct(private string \$apiKey) {}\n}\n?>"],
    19=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.inheritance.php', 'title' => 'Inheritance', 'snippet' => "<?php\nclass Admin extends User {\n    public function getRole() { return 'Admin'; }\n}\n?>"],
    20=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.interfaces.php', 'title' => 'Interfaces', 'snippet' => "<?php\ninterface Logger {\n    public function log(string \$msg);\n}\n?>"],
    21=> ['url' => 'https://www.php.net/manual/pt_BR/book.pdo.php', 'title' => 'SQL Basics', 'snippet' => "CREATE TABLE users (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    email VARCHAR(255) UNIQUE NOT NULL\n);"],
    22=> ['url' => 'https://www.php.net/manual/pt_BR/pdo.connections.php', 'title' => 'PDO Connection', 'snippet' => "<?php\n\$pdo = new PDO('mysql:host=localhost;dbname=test', 'root', '');\n?>"],
    23=> ['url' => 'https://www.php.net/manual/pt_BR/pdo.prepared-statements.php', 'title' => 'Prepared Statements', 'snippet' => "<?php\n\$stmt = \$pdo->prepare('SELECT * FROM users WHERE id = ?');\n\$stmt->execute([\$id]);\n?>"],
    24=> ['url' => 'https://www.php.net/manual/pt_BR/pdostatement.execute.php', 'title' => 'CRUD Operations', 'snippet' => "<?php\n\$stmt = \$pdo->prepare(\"INSERT INTO users (name) VALUES (:name)\");\n\$stmt->execute(['name' => \$data]);\n?>"],
    25=> ['url' => 'https://www.php.net/manual/pt_BR/book.pdo.php', 'title' => 'JOIN Queries', 'snippet' => "SELECT u.name, p.title \nFROM users u \nJOIN posts p ON u.id = p.user_id;"],
    26=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.architecture.php', 'title' => 'MVC Pattern', 'snippet' => "<?php\n// Router invokes Controller, passes Model data to View\n\$controller = new UserController(new UserModel());\n?>"],
    27=> ['url' => 'https://www.php.net/manual/pt_BR/reserved.variables.server.php', 'title' => 'Routing', 'snippet' => "<?php\n\$uri = parse_url(\$_SERVER['REQUEST_URI'], PHP_URL_PATH);\nif (\$uri === '/about') { require 'about.php'; }\n?>"],
    28=> ['url' => 'https://www.php.net/manual/pt_BR/language.basic-syntax.phpmode.php', 'title' => 'Templating', 'snippet' => "<h1><?= htmlspecialchars(\$title) ?></h1>"],
    29=> ['url' => 'https://www.php.net/manual/pt_BR/function.password-hash.php', 'title' => 'Password Hashing', 'snippet' => "<?php\n\$hash = password_hash('super_secret_123', PASSWORD_ARGON2ID);\n?>"],
    30=> ['url' => 'https://www.php.net/manual/pt_BR/function.password-verify.php', 'title' => 'Authentication', 'snippet' => "<?php\nif (password_verify(\$passwordAtmpt, \$userHash)) {\n    \$_SESSION['auth'] = true;\n}\n?>"],
    31=> ['url' => 'https://www.php.net/manual/pt_BR/features.sessions.php', 'title' => 'Authorization & Roles', 'snippet' => "<?php\nif (!in_array('admin', \$_SESSION['roles'])) {\n    http_response_code(403);\n    die('Forbidden');\n}\n?>"],
    32=> ['url' => 'https://www.php.net/manual/pt_BR/security.php', 'title' => 'Web Security', 'snippet' => "<?php\n// Prevent XSS\n\$safe = htmlspecialchars(\$unsafeStr, ENT_QUOTES, 'UTF-8');\n?>"],
    33=> ['url' => 'https://www.php.net/manual/pt_BR/book.json.php', 'title' => 'JSON & REST', 'snippet' => "<?php\nheader('Content-Type: application/json');\necho json_encode(['status' => 'success', 'data' => []]);\n?>"],
    34=> ['url' => 'https://www.php.net/manual/pt_BR/book.curl.php', 'title' => 'External APIs (cURL)', 'snippet' => "<?php\n\$ch = curl_init('https://api.github.com/users/octocat');\ncurl_setopt(\$ch, CURLOPT_RETURNTRANSFER, true);\n\$response = curl_exec(\$ch);\n?>"],
    35=> ['url' => 'https://www.php.net/manual/pt_BR/reserved.variables.server.php', 'title' => 'Building APIs', 'snippet' => "<?php\nif (\$_SERVER['REQUEST_METHOD'] === 'POST') {\n    // Create resource\n}\n?>"],
    36=> ['url' => 'https://www.php.net/manual/pt_BR/language.namespaces.rationale.php', 'title' => 'Composer & PSR-4', 'snippet' => "<?php\nrequire 'vendor/autoload.php';\nuse App\\Models\\User;\n?>"],
    37=> ['url' => 'https://www.php.net/manual/pt_BR/book.errorfunc.php', 'title' => 'Error Handling', 'snippet' => "<?php\ntry {\n    // risky logic\n} catch (Exception \$e) {\n    error_log(\$e->getMessage());\n}\n?>"],
    38=> ['url' => 'https://www.php.net/manual/pt_BR/book.datetime.php', 'title' => 'Dates & Times', 'snippet' => "<?php\n\$dt = new DateTime();\necho \$dt->format('Y-m-d H:i:s');\n?>"],
    39=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.php', 'title' => 'Architecture', 'snippet' => "<?php\n// Design patterns, Dependency Injection\n\$app = new Application(new Database());\n?>"],
    40=> ['url' => 'https://www.php.net/manual/pt_BR/language.oop5.php', 'title' => 'Implementation', 'snippet' => "<?php\n// Final testing & deployment checks\n?>"]
];
